# syntax=docker/dockerfile:1
ARG NODE_VERSION=node:22.14.0
FROM node:${NODE_VERSION}-alpine

WORKDIR /app
RUN chown node:node /app
USER node

COPY --chown=node:node package*.json .
RUN --mount=type=cache,target=/home/node/.npm \
    npm ci --omit=dev

COPY --chown=node:node . .

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:8000/health || exit 1

EXPOSE 8000
CMD ["node", "dist/server.js"]