# Lightweight Node image with npm
FROM node:22.14.0-alpine

# Set working directory
WORKDIR /app

# Install dependencies first for better caching
COPY package.json package-lock.json ./

RUN npm install

# Copy the rest of the source files into the image.(excluded in .dockerignore)
COPY . .

# Expose the port that the application listens on. (Vite's default port)
EXPOSE 5174

# Start Vite dev server with HMR
CMD npm run dev
# CMD ["npm", "run", "dev"]